/*

 EMPTY_FACTORY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define empty_factoryWidth 32
#define empty_factoryHeight 32
#define empty_factoryBank 0

#define empty_factory empty_factoryPLN0
extern unsigned char empty_factoryPLN0[];

/* End of EMPTY_FACTORY.H */
