/*

 EXAMPLE_FACTORY_1_SMALL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : tiles_small.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define example_factory_1_smallWidth 32
#define example_factory_1_smallHeight 32
#define example_factory_1_smallBank 0

extern unsigned char example_factory_1_small[];

/* End of EXAMPLE_FACTORY_1_SMALL.H */
