/*

 EXAMPLE_FACTORY_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : tiles_large.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define example_factory_1Width 40
#define example_factory_1Height 18
#define example_factory_1Bank 0

extern unsigned char example_factory_1[];

/* End of EXAMPLE_FACTORY_1.H */
