/*

 TILES_SMALL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 47

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles_smallBank 0

/* Super Gameboy palette 0 */
#define tiles_smallSGBPal0c0 6076
#define tiles_smallSGBPal0c1 8935
#define tiles_smallSGBPal0c2 6596
#define tiles_smallSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles_smallSGBPal1c0 6076
#define tiles_smallSGBPal1c1 8935
#define tiles_smallSGBPal1c2 6596
#define tiles_smallSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles_smallSGBPal2c0 6076
#define tiles_smallSGBPal2c1 8935
#define tiles_smallSGBPal2c2 6596
#define tiles_smallSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles_smallSGBPal3c0 6076
#define tiles_smallSGBPal3c1 8935
#define tiles_smallSGBPal3c2 6596
#define tiles_smallSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles_smallCGBPal0c0 6076
#define tiles_smallCGBPal0c1 8935
#define tiles_smallCGBPal0c2 6596
#define tiles_smallCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define tiles_smallCGBPal1c0 6076
#define tiles_smallCGBPal1c1 8935
#define tiles_smallCGBPal1c2 6596
#define tiles_smallCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define tiles_smallCGBPal2c0 6076
#define tiles_smallCGBPal2c1 8935
#define tiles_smallCGBPal2c2 6596
#define tiles_smallCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define tiles_smallCGBPal3c0 6076
#define tiles_smallCGBPal3c1 8935
#define tiles_smallCGBPal3c2 6596
#define tiles_smallCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define tiles_smallCGBPal4c0 6076
#define tiles_smallCGBPal4c1 8935
#define tiles_smallCGBPal4c2 6596
#define tiles_smallCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define tiles_smallCGBPal5c0 6076
#define tiles_smallCGBPal5c1 8935
#define tiles_smallCGBPal5c2 6596
#define tiles_smallCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define tiles_smallCGBPal6c0 6076
#define tiles_smallCGBPal6c1 8935
#define tiles_smallCGBPal6c2 6596
#define tiles_smallCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define tiles_smallCGBPal7c0 6076
#define tiles_smallCGBPal7c1 8935
#define tiles_smallCGBPal7c2 6596
#define tiles_smallCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char tiles_small[];

/* End of TILES_SMALL.H */
